language: node_js
node_js:
- '8.11'
branches:
  only:
  - develop
script:
- npm run build
- npm run firebase:deploy
notifications:
  slack:
    rooms:
      secure: lxH1zn6wXA4+WuqDRUFTePBCBIzkFAS99EgPYeaJKJ6ignwwHoGqn3ciKAbDD5VqmQU+N8I8f2aAO/Ti3zMcL9Gh0zJaVYK3bXBAmUk+/OKOypWNP/oyOh7FJFmaaLcmJawPRvnJ8iGK5VyVB4o/n8tFg4AqxTphy0eDeDLTIAFoI3v5r3zViAbKCeiw1M5JGUhaCzj79icPM1zcoNoP8CuLzGRdvEqQuIXxopta1tmggMKcjpKyGqZgsVdCNUVfxpOE481ZO6GUfw33cIgJDDyvCo17ijuUB06JTqFpEQ566VadKTz22VdzhvqQIE6A5BnyNNFMT4mMISN22pikOnqHN6UWPIW0p1loZOKRT7bZ81n2889LVRWlQxETO8ooAkvBRjv0Uk3mutMGyAeLCZK3tgyF3zMNWt5pXRQjCNcz10emzLT1NYA+jVnrEPGM6jLgUu33UicEfXD78/PpIh3M70JaP+qFjhB3VSSD+jvdquaXqlWVBnzqzvZDxEbXnbDqYqFQOkPo9tHUw/xzIdYVa30daxVmF+pzqHGCyolILByjrj+r/oaPUQLuI/QQxaUnYLNh5y3EIaXYucUXPm4x/gAH8cl9tzqF5kBCwXYO/2m2z93afLI26RkDnQqEYfyZRBCUKc7zC86ZjRwVAKjMN5WWf8GByoyHpTCL9bg=
env:
  global:
  - secure: AYkLA5NELZRYFHJiEfxtumdAFme2/a+LlyBWG+92WFBl9+J24L3sTBRTI7P68959iUhdkfMGfO1U48ldvFRd8JD2qMqBV4xnQ95Oai1Dr+uJlNICuTFIqO87dlv7GeO/vyEtg8BeCLEpjn992mqDwDa1k3jfK+76IHLV2FX7uQb7oVnjVzg7bJpKXM6u9cEeeLcdXdItwcl4OgcEYBgSXvpjlc1HgwUhTq1M3MymH3JaOodp5S2EFuw5H6LHzPA6Hnd0uAUQgpPEOBJbbKrvi6O8KCPl5l8Hlqb2EuPLGlOgqselyW3bHzE/waPy/sBXarm3K8yUshwMr2hntcrgxrJFiJDT+MjSg3/cHymtyZCeX2jpQvOIfClo8kfUafqVr+5J8UVBx0mfh7hGwG47yh5qLorZ9BO/Qn3HIfVgxIHNstuQRXhqcdndLuU9mzSUsKR3K8PcTd06w/6BoZ2BubY8hEvhYsQjes5jogAvq10eDEt4lAwngADB+WFBSIiOQKPkR8pLPZxqS/XhP+H7w7UIOFWsxHL4wbKHSJxBQYIoxSZOW48GqdOs+acPbPtjXqo1jZSSWEN5vlUH+XWNmQ57eiFowm8jAK10B6h6zAqDidSS1vn37dkZ6Es3C9JxDd8VsAjB3TXxkspLQX6b3nZIt0LRXn/dU264c+U/dBQ=
